name: 'Run Test Cases'

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout search_vulns code
        uses: actions/checkout@v3

      - name: Set up Python and Pip
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: '3.8'

      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip3 install -r requirements.txt

      - name: Install tool and build DB
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: NVD_API_KEY=$NVD_API_KEY ./install.sh --full

      - name: Test CVE Completeness
        run: python3 ./tests/test_cve_completeness.py

      - name: Test Exploit Completeness
        run: python3 ./tests/test_exploit_completeness.py
